server:
  port: 8080

spring:
  cloud:
    gateway:

      # ENABLE automatic forwarding of X-Forwarded-For, X-Forwarded-Proto, etc.
      forwarded:
        enabled: true

      default-filters:
        # Forward the original client IP to downstream microservices
        - AddRequestHeader=X-Forwarded-For, #{request.remoteAddress.address.hostAddress}

      routes:

        # AUTH SERVICE (ALLOW login/register without token)
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1   # option, recommend for clean paths

        # USER MICRO-SERVICE
        - id: service-user
          uri: http://localhost:9001
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        # ORDER MICRO-SERVICE
        - id: service-order
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
