server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # Important when using lb://

      default-filters:
        - AddRequestHeader=X-Forwarded-For, Passed

      routes:
        # ================== AUTH SERVICE ==================
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20

        # ================== USER SERVICE ==================
        - id: service-user
          uri: lb://SERVICE-USER    # MUST MATCH Eureka
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 500
                  requestedTokens: 100

        # ================== ORDER SERVICE ==================
        - id: service-order
          uri: lb://SERVICE-ORDER   # MUST MATCH Eureka
          predicates:
            - Path=/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 500
                  requestedTokens: 100

  data:
    redis:
      host: 172.23.28.102
      port: 6379

# ========= Eureka Registration =========
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

# ========= Distributed Tracing (Optional) =========
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
