server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: service-user
          uri: http://localhost:9001
          predicates:
            - Path=/users/**
        - id: service-order
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
