server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true   # Important when using lb://

      default-filters:
        - AddRequestHeader=X-Forwarded-For, Passed

      routes:
        # ================== AUTH SERVICE ==================
        # Uses Sticky Sessions (configured in Java StickyLBConfig)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/auth/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 10
                  burstCapacity: 20

        # ================== USER SERVICE ==================
        # Uses Round Robin (Default behavior)
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/users/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 800
                  requestedTokens: 100

        # ================== ORDER SERVICE ==================
        # Uses Random selection (configured in Java RandomLBConfig)
        - id: service-order
          uri: lb://service-order
          predicates:
            - Path=/orders/**
          filters:
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter:
                  replenishRate: 1
                  burstCapacity: 800
                  requestedTokens: 100

  # Redis configuration for Rate Limiting
  data:
    redis:
      host: 172.23.28.102
      port: 6379

# ========= Eureka Registration =========
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: api-gateway:${server.port}

# ========= Distributed Tracing =========
management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  endpoints:
    web:
      exposure:
        include: "*" # Useful for debugging and monitoring
