server:
  port: 8080

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Forwarded-For, Passed

      routes:
        # ================== AUTH SERVICE ==================
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          filters:
            # Public login/register — limit by IP
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10    # 10 requests per second
                redis-rate-limiter.burstCapacity: 20    # max burst

        # ================== USER SERVICE ==================
        - id: user-service
          uri: http://localhost:9001
          predicates:
            - Path=/users/**
          filters:
            # Secured APIs — limit by USER ID from JWT
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 5     # 5 req/sec per user
                redis-rate-limiter.burstCapacity: 10

        # ================== ORDER SERVICE ==================
        - id: order-service
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
          filters:
            # Secured APIs — limit by USER ID from JWT
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 3     # 3 req/sec per user
                redis-rate-limiter.burstCapacity: 5
