server:
  port: 8080

spring:
  cloud:
    gateway:

      forwarded:
        enabled: true

      routes:

        # AUTH SERVICE (NO X-Forwarded-For)
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        # USER MICRO-SERVICE
        - id: service-user
          uri: http://localhost:9001
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-For, #{request.remoteAddress.hostString}

        # ORDER MICRO-SERVICE
        - id: service-order
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Forwarded-For, #{request.remoteAddress.hostString}
