server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://service-user
          predicates:
            - Path=/users/**
        - id: order-service
          uri: lb://service-order
          predicates:
            - Path=/orders/**
