server:
  port: 8080

spring:
  main:
    web-application-type: reactive

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: http://localhost:9001
              predicates:
                - Path=/users/**
            - id: order-service
              uri: http://localhost:9002
              predicates:
                - Path=/orders/**
