server:
  port: 8080

spring:
  application:
    name: api-gateway

  redis:
    host: localhost
    port: 6379

  cloud:
    gateway:
      default-filters:
        - AddRequestHeader=X-Forwarded-For, Passed

      routes:
        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          filters:
            # Rate limit based on IP (no JWT for login/register)
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@ipKeyResolver}"
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20

        - id: service-user
          uri: http://localhost:9001
          predicates:
            - Path=/users/**
          filters:
            # Rate limit based on LOGGED IN USER JWT
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 5
                redis-rate-limiter.burstCapacity: 10

        - id: service-order
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
          filters:
            # Rate limit based on LOGGED IN USER JWT
            - name: RequestRateLimiter
              args:
                key-resolver: "#{@userKeyResolver}"
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 5
