server:
  port: 8080

spring:
  cloud:
    gateway:

      forwarded:
        enabled: true

      routes:

        - id: auth-service
          uri: http://localhost:9000
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1

        - id: service-user
          uri: http://localhost:9001
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1

        - id: service-order
          uri: http://localhost:9002
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
