server:
  port: 9000

spring:
  application:
    name: auth-service

jwt:
  secret: 8d1f3c9b7e624a1d98b39e4fd8712a4c56f8912cd3b45ef98ab12cd8934fa12c
  expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    hostname: localhost     # Forces Eureka to use localhost
    instance-id: auth-service:${server.port}   # Optional but helps debugging
management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
