server:
  port: 9011

spring:
  application:
    name: service-user
custom:
  message: "✅ Config loaded successfully from Git!"

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
