server:
  port: 9001

spring:
  application:
    name: service-user

  cloud:
    loadbalancer:
      retry:
        enabled: true   # service-user calls service-order

custom:
  message: "✅ Config loaded successfully from Git!"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: service-user:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
resilience4j:
  circuitbreaker:
    instances:
      orderCB:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5

        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s

        permitted-number-of-calls-in-half-open-state: 3
        wait-duration-in-open-state: 10s

        automatic-transition-from-open-to-half-open-enabled: true
