server:
  port: 9001

spring:
  application:
    name: service-user

  cloud:
    loadbalancer:
      retry:
        enabled: true   # ⬅️ Required because service-user calls service-order

custom:
  message: "✅ Config loaded successfully from Git!"

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: service-user:${server.port}

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
