server:
  port: 9001

spring:
  application:
    name: service-user

  cloud:
    openfeign:
      micrometer:
        enabled: true   # ⬅️ REQUIRED for Zipkin tracing of Feign calls

management:
  tracing:
    sampling:
      probability: 1.0   # 100% tracing

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans  # Zipkin collector

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true    # Ensures Eureka registers IP not hostname
    instance-id: ${spring.application.name}:${server.port}
    hostname: localhost        # ⬅️ Prevents HOSTNAME from becoming DESKTOP-XXXX

custom:
  message: "✅ Config loaded successfully from Git!"
