server:
  port: 9002

spring:
  application:
    name: service-order

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    hostname: localhost     # Forces Eureka to use localhost
    instance-id: service-order:${server.port}   # Optional but helps debugging

management:
  tracing:
    sampling:
      probability: 1.0

  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
