server:
  port: 9001

spring:
  application:
    name: service-user

  cloud:
    loadbalancer:
      retry:
        enabled: false

  okhttp:
    enabled: true       # ✅ REQUIRED for timeout testing

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    prefer-ip-address: true
    instance-id: service-user:${server.port}

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000

# ============================
# RESILIENCE4J CONFIG
# ============================
resilience4j:

  circuitbreaker:
    instances:
      orderCB:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 5
        minimum-number-of-calls: 3
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2
        automatic-transition-from-open-to-half-open-enabled: true

  timelimiter:
    instances:
      orderCB:                # ✅ SAME NAME AS CIRCUIT BREAKER
        timeout-duration: 3s  # ✅ THIS is where timeout belongs
        cancel-running-future: true

  retry:
    instances:
      orderRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - feign.FeignException

management:
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers,circuitbreakerevents
